site_name: Stay Safe
theme:
  logo: assets/logo.png
  favicon: images/favicon.png
  name: material
  font:
    text: Trueno
  features:
    - navigation.instant
    - navigation.tabs
extra_css:
  - stylesheets/styles.css

dev_addr: "0.0.0.0:8000"
